# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tlp', models.CharField(choices=[('1', 'Red'), ('2', 'Amber'), ('3', 'Green'), ('4', 'White')], max_length=1)),
                ('attack', models.CharField(choices=[('1', 'Other'), ('2', 'Malware'), ('3', 'Phishing'), ('4', 'Fraud')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('1', 'sha256'), ('2', 'sha1'), ('3', 'md5'), ('4', 'URL'), ('5', 'domain'), ('6', 'registry'), ('7', 'file'), ('8', 'source'), ('9', 'free text')], max_length=2)),
                ('value', models.CharField(max_length=2048)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
