# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_incident_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
