# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170626_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='tags',
            field=models.ManyToManyField(null=True, to='core.Tag'),
        ),
    ]
